### ISSUE TITLE
Error with GraphQL plugin

### ISSUE THREAD

**Issue by arnaudjnn** [pouyamiralayi/import-plugin#3]
Error: [GraphQL] Cannot find action "plugins::import-content.importconfig.findOne". Check your graphql configurations.

**Comment by pouyamiralayi** [comment]
@arnaudjnn please use [migrate_to_19.4 ](https://github.com/pouyamiralayi/strapi-import-content-plugin-tutorial/tree/migrate_to_19.4) branch which is compatible with graphql (offers the missing endpoints for graphql to works correctly) and is based on Strapi 19.4.
Cheers!
